version: '3.7'

services:
  task_manager_api:
    build: .
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - 8000:8000
    depends_on:
      - task_manager_db
    environment: &api-environment
      DJANGO_ENV: dev
      DJANGO_SECRET_KEY: dev
    command: python manage.py runserver 0.0.0.0:8000

  task_manager_db:
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin