version: '3.7'

services:
  task_manager_api:
    build: .
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - 8000:8000
    depends_on:
      - task_manager_db
      - pgadmin
    environment: &api-environment
      DJANGO_ENV: dev
      DJANGO_SECRET_KEY: dev
      DATABASE_NAME: task_manager
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_HOST: task_manager_db
      DATABASE_PORT: 5432
    command: python manage.py runserver 0.0.0.0:8000

  task_manager_db:
    image: postgres:15.4
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  pgadmin:
    image: dpage/pgadmin4:7.7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 3330663@internet.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - task_manager_db